let layer4 = new Element(DIV);
layer4.set_id("layer4");
layer4.set_width("100%");
layer4.set_height("15%");
layer4.set_position("absolute");
//layer4.set_backgroundColor("#7F7F7F");
layer4.set_top("167%");
layer4.set_left("0px");
layer4.set_margin("0px 0px 0px 0px");
layer4.set_padding("0% 0px 0px 0px");
layer4.set_innerHTML("Th&egraveme du mariage");
layer4.set_fontFamily("Supermercado One");
layer4.set_fontSize("250%");
//layer4.set_color("#FFFFFF");
layer4.set_fontWeight("bold");
layer4.set_textAlign("center");
layer4.set_color("#FFFFFF");
//document.body.appendChild(layer4.element());
