let theme = new Element(DIV);
theme.set_id("theme");
theme.set_width("90%");
theme.set_height("50%");
theme.set_position("absolute");
//theme.set_backgroundColor("#7F7F7F");
theme.set_top("50%");
theme.set_left("5%");
theme.set_margin("0px 0px 0px 0px");
theme.set_padding("0px 0px 0px 0px");
theme.set_innerHTML("Le th&egraveme du mariage est le bleu ! Un v&ecirctement, un accessoire, un objet... Tant de possibilit&eacutes pour &ecirctre &agrave la couleur du jour !");
theme.set_fontFamily("Supermercado One");
theme.set_fontSize("75%");
theme.set_color("#4169e1");
theme.set_fontWeight("bold");
theme.set_textAlign("center");
theme.set_parent(layer4);
