let layer4Benjamin = new Element(DIV);
layer4Benjamin.set_id("layer4Benjamin");
layer4Benjamin.set_width("50%");
layer4Benjamin.set_height("50%");
layer4Benjamin.set_position("absolute");
//layer4Benjamin.set_backgroundColor("#7F7F7F");
layer4Benjamin.set_top("50%");
layer4Benjamin.set_left("50%");
layer4Benjamin.set_margin("0px 0px 0px 0px");
layer4Benjamin.set_padding("0px 0px 0px 0px");
layer4Benjamin.set_innerHTML("Benjamin : 06 16 15 89 29");
layer4Benjamin.set_fontFamily("Supermercado One");
layer4Benjamin.set_fontSize("75%");
//layer4Benjamin.set_color("#FFFFFF");
layer4Benjamin.set_fontWeight("bold");
layer4Benjamin.set_textAlign("center");
layer4Benjamin.set_color("#FFFFFF");
layer4Benjamin.set_parent(layer5);
