let layer5 = new Element(DIV);
layer5.set_id("layer5");
layer5.set_width("100%");
layer5.set_height("15%");
layer5.set_position("absolute");
//layer5.set_backgroundColor("#7F7F7F");
layer5.set_top("167%");
layer5.set_left("0px");
layer5.set_margin("0px 0px 0px 0px");
layer5.set_padding("0% 0px 0px 0px");
layer5.set_innerHTML("Contacts");
layer5.set_fontFamily("Supermercado One");
layer5.set_fontSize("250%");
layer5.set_innerHTML("Contacts");
//layer5.set_color("#FFFFFF");
layer5.set_fontWeight("bold");
layer5.set_textAlign("center");
layer5.set_color("#FFFFFF");
//document.body.appendChild(layer5.element());
