let layer1Buttons = new Element(DIV);
layer1Buttons.set_id("layer1Buttons");
layer1Buttons.set_width("90%");
layer1Buttons.set_height("10%");
layer1Buttons.set_position("absolute");
//layer1Buttons.set_backgroundColor("#F4C0AF");
layer1Buttons.set_top("0%");
layer1Buttons.set_left("5%");
layer1Buttons.set_margin("0% 0% 0% 0%");
layer1Buttons.set_padding("0% 0% 0% 0%");
layer1Buttons.set_display("flex");
layer1Buttons.set_justify_content("space-between");
layer1Buttons.set_align_items("center");
document.body.appendChild(layer1Buttons.element());
