let layer1LeftPicture = new Element(IMG);
layer1LeftPicture.set_id("layer1LeftPicture");
layer1LeftPicture.set_position("absolute");
layer1LeftPicture.set_src(rpath + "assets/marinebenjamin_mariage1.jpg");
layer1LeftPicture.set_width("30%");
layer1LeftPicture.set_height("98%");
layer1LeftPicture.set_top("2%");
layer1LeftPicture.set_left("3.5%");
layer1LeftPicture.set_margin("0px 0px 0px 0px");
layer1LeftPicture.set_padding("0px 0px 0px 0px");
layer1LeftPicture.set_overflowX("hidden");
//layer1LeftPicture.set_display("flex");
layer1LeftPicture.set_parent(layer1);
