let layer1LeftPicture = new Element(IMG);
layer1LeftPicture.set_id("layer1LeftPicture");
layer1LeftPicture.set_src(rpath + "assets/IMG_20221027_134454.png");
layer1LeftPicture.set_width("50%");
layer1LeftPicture.set_height("100%");
layer1LeftPicture.set_top("0px");
layer1LeftPicture.set_left("0px");
layer1LeftPicture.set_margin("0px 0px 0px 0px");
layer1LeftPicture.set_padding("0px 0px 0px 0px");
layer1LeftPicture.set_overflowX("hidden");
layer1LeftPicture.set_display("flex");
layer1LeftPicture.set_parent(layer1);
