let layer1ListeMariageButton = new Element(BUTTON);
layer1ListeMariageButton.set_id("layer1ListeMariageButton");
layer1ListeMariageButton.set_backgroundColor("transparent")
layer1ListeMariageButton.set_border("0px");
//layer1ListeMariageButton.set_outline("0px");
//layer1ListeMariageButton.set_width("20%");
//layer1ListeMariageButton.set_height("40%");
layer1ListeMariageButton.set_textContent("Liste de mariage");
layer1ListeMariageButton.set_textAlign("center");
//layer1ListeMariageButton.set_color("#FFFFFF");
layer1ListeMariageButton.set_fontFamily("Supermercado One");
layer1ListeMariageButton.set_fontSize("200%");
layer1ListeMariageButton.set_fontWeight("bold");
//layer1ListeMariageButton.set_position("absolute");
layer1ListeMariageButton.set_padding("0% 0% 0% 0%");
layer1ListeMariageButton.set_margin("0% 0% 0% 0%");
//layer1ListeMariageButton.set_borderRadius("10px");
//layer1ListeMariageButton.set_border("solid #4169E1 2px");
//layer1ListeMariageButton.set_left("50%");
//layer1ListeMariageButton.set_top("30%");
layer1ListeMariageButton.set_cursor("pointer");
layer1ListeMariageButton.set_functionOnClick( open_liste_mariage );
layer1ListeMariageButton.set_parent(layer1Buttons);