let meuble1 = new Element(DIV);
meuble1.set_id("meuble1");
meuble1.set_width("50%");
meuble1.set_height("100%");
meuble1.set_position("absolute");
meuble1.set_top("220%");
meuble1.set_left("0%");
meuble1.set_margin("0px 0px 0px 0px");
meuble1.set_padding("0px 0px 0px 0%");
//meuble1.set_parent(layer3);

let meuble1Img = new Element(IMG);
meuble1Img.set_id("meuble1Img");
meuble1Img.set_src(rpath + "../../assets/meuble1.PNG");
meuble1Img.set_width("75%");
meuble1Img.set_height("90%");
meuble1Img.set_position("absolute");
meuble1Img.set_top("0%");
meuble1Img.set_left("10%");
meuble1Img.set_margin("0px 0px 0px 0px");
meuble1Img.set_padding("0px 0px 0px 0px");
meuble1Img.set_parent(meuble1);

let meuble1Text = new Element(DIV);
meuble1Text.set_id("layer2Text");
meuble1Text.set_position("absolute");
meuble1Text.set_width("75%");
meuble1Text.set_height("10%");
meuble1Text.set_left("10%");
meuble1Text.set_top("90%");
meuble1Text.set_margin("0% 0% 0px 0px");
meuble1Text.set_padding("0% 0px 0px 0px");
meuble1Text.set_innerHTML("Meuble : 158&#8364");
meuble1Text.set_fontFamily("Supermercado One");
meuble1Text.set_fontSize("250%");
//meuble1Text.set_color("#FFFFFF");
meuble1Text.set_fontWeight("bold");
meuble1Text.set_textAlign("center");
meuble1Text.set_parent(meuble1);
